import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const encoder = new TextEncoder();
const decoder = new TextDecoder();
function json(data: unknown, status = 200) { return Response.json(data, { status, headers: { "Cache-Control": "no-store", "X-Content-Type-Options": "nosniff" } }); }
function fromB64url(value: string) { const normalized = value.replace(/-/g, "+").replace(/_/g, "/"); const padded = normalized + "=".repeat((4 - (normalized.length % 4)) % 4); const binary = atob(padded); return Uint8Array.from(binary, c => c.charCodeAt(0)); }
function fromBase64(value: string) { try { const binary = atob(value); return Uint8Array.from(binary, c => c.charCodeAt(0)); } catch { return new Uint8Array(); } }
function equal(a: Uint8Array, b: Uint8Array) { if (a.length !== b.length) return false; let diff = 0; for (let i = 0; i < a.length; i++) diff |= a[i] ^ b[i]; return diff === 0; }
async function rest(path: string, init: RequestInit = {}) { const base = Deno.env.get("SUPABASE_URL")!; const service = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!; return fetch(`${base}/rest/v1/${path}`, { ...init, headers: { apikey: service, Authorization: `Bearer ${service}`, "Content-Type": "application/json", ...(init.headers || {}) } }); }
async function cryptoKey() { const response = await rest("limitless_provider_crypto_material?id=eq.production&select=key_jwk"); if (!response.ok) throw new Error("credential key unavailable"); const rows = await response.json() as Array<{ key_jwk?: JsonWebKey }>; const k = typeof rows[0]?.key_jwk?.k === "string" ? rows[0]!.key_jwk!.k! : ""; if (!k) throw new Error("credential key unavailable"); const raw = fromB64url(k); if (raw.byteLength !== 32) throw new Error("credential key invalid"); return crypto.subtle.importKey("raw", raw, { name: "AES-GCM" }, false, ["decrypt"]); }
async function whopCredential(brandId: string) { const response = await rest(`limitless_provider_credentials_v2?brand_id=eq.${encodeURIComponent(brandId)}&provider=eq.whop&select=iv,ciphertext`); if (!response.ok) throw new Error("credential unavailable"); const rows = await response.json() as Array<{ iv?: string; ciphertext?: string }>; const row = rows[0]; if (!row?.iv || !row?.ciphertext) throw new Error("credential unavailable"); const key = await cryptoKey(); const decrypted = await crypto.subtle.decrypt({ name: "AES-GCM", iv: fromB64url(row.iv), additionalData: encoder.encode(`limitless:${brandId}:whop:v2`) }, key, fromB64url(row.ciphertext)); const value = JSON.parse(decoder.decode(decrypted)) as { companyId?: string; apiKey?: string; webhookSecret?: string }; const companyId = typeof value.companyId === "string" ? value.companyId : ""; const apiKey = typeof value.apiKey === "string" ? value.apiKey : ""; const webhookSecret = typeof value.webhookSecret === "string" ? value.webhookSecret : ""; if (!/^biz_[A-Za-z0-9]+$/.test(companyId) || !apiKey || !/^(?:ws_|whsec_)[A-Za-z0-9+/_=-]{8,}$/.test(webhookSecret)) throw new Error("webhook signing unavailable"); return { companyId, apiKey, webhookSecret }; }
async function verifySignature(raw: string, headers: Headers, secret: string) { const webhookId = headers.get("webhook-id") || ""; const timestamp = headers.get("webhook-timestamp") || ""; const signatureHeader = headers.get("webhook-signature") || ""; if (!/^msg_[A-Za-z0-9]+$/.test(webhookId) || !/^\d{10}$/.test(timestamp) || !signatureHeader) return { ok: false as const, webhookId }; const timestampMs = Number(timestamp) * 1000; if (!Number.isSafeInteger(timestampMs) || Math.abs(Date.now() - timestampMs) > 5 * 60 * 1000) return { ok: false as const, webhookId }; const key = await crypto.subtle.importKey("raw", encoder.encode(secret), { name: "HMAC", hash: "SHA-256" }, false, ["sign"]); const expected = new Uint8Array(await crypto.subtle.sign("HMAC", key, encoder.encode(`${webhookId}.${timestamp}.${raw}`))); const candidates = signatureHeader.split(/\s+/).filter(Boolean).map(part => part.startsWith("v1,") ? fromBase64(part.slice(3)) : new Uint8Array()); return { ok: candidates.some(candidate => equal(candidate, expected)), webhookId } as const; }
async function reconcile(brandId: string, attemptId: string, paymentId: string) { const base = Deno.env.get("SUPABASE_URL")!; const service = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!; const response = await fetch(`${base}/functions/v1/limitless-payment-reconciler`, { method: "POST", headers: { Authorization: `Bearer ${service}`, apikey: service, "Content-Type": "application/json" }, body: JSON.stringify({ brandId, attemptId, paymentId }), signal: AbortSignal.timeout(30000) }); let payload: Record<string, unknown> = {}; try { payload = await response.json() as Record<string, unknown>; } catch { /* no-op */ } if (!response.ok) { const detail = typeof payload.error === "string" ? payload.error : "payment reconciliation failed"; throw new Error(detail); } return payload; }

Deno.serve(async (req: Request) => {
  if (req.method !== "POST") return json({ error: "Method not allowed." }, 405);
  const brandId = new URL(req.url).searchParams.get("brand") || "";
  if (!/^brand_[A-Za-z0-9-]+$/.test(brandId)) return json({ error: "Invalid brand." }, 404);
  const length = Number(req.headers.get("content-length") || "0");
  if (Number.isFinite(length) && length > 65536) return json({ error: "Payload too large." }, 413);
  const raw = await req.text(); if (encoder.encode(raw).byteLength > 65536) return json({ error: "Payload too large." }, 413);
  try {
    const credential = await whopCredential(brandId);
    const signature = await verifySignature(raw, req.headers, credential.webhookSecret);
    if (!signature.ok) return json({ error: "Invalid webhook signature." }, 401);
    let event: Record<string, unknown>; try { event = JSON.parse(raw) as Record<string, unknown>; } catch { return json({ error: "Invalid webhook payload." }, 400); }
    if (event.id !== signature.webhookId || event.api_version !== "v1" || event.type !== "payment.succeeded" || !event.data || typeof event.data !== "object" || Array.isArray(event.data)) return json({ error: "Invalid webhook event." }, 400);
    const data = event.data as Record<string, unknown>; const paymentId = typeof data.id === "string" && /^pay_[A-Za-z0-9]+$/.test(data.id) ? data.id : undefined; const metadata = data.metadata && typeof data.metadata === "object" && !Array.isArray(data.metadata) ? data.metadata as Record<string, unknown> : {}; const attemptId = typeof metadata.limitless_attempt_id === "string" && /^attempt_[0-9a-f-]{36}$/.test(metadata.limitless_attempt_id) ? metadata.limitless_attempt_id : undefined;
    const envelopeAccountId = typeof event.account_id === "string" ? event.account_id : typeof event.company_id === "string" ? event.company_id : ""; const paymentCompany = data.company && typeof data.company === "object" && !Array.isArray(data.company) ? data.company as Record<string, unknown> : {}; const paymentCompanyId = typeof paymentCompany.id === "string" ? paymentCompany.id : ""; const accountMatchesBrand = envelopeAccountId === credential.companyId || paymentCompanyId === credential.companyId;
    if (attemptId && !accountMatchesBrand) return json({ error: "Webhook account mismatch." }, 422);
    const stored = { id: signature.webhookId, type: "payment.succeeded", accountId: envelopeAccountId || paymentCompanyId, accountMatchesBrand, syntheticTest: !attemptId, ...(paymentId ? { resourceId: paymentId, paymentId } : {}), ...(attemptId ? { attemptId } : {}), receivedAt: new Date().toISOString() };
    const recorded = await rest("rpc/limitless_record_whop_webhook_event", { method: "POST", body: JSON.stringify({ p_event_id: signature.webhookId, p_brand_id: brandId, p_event: stored }) }); if (!recorded.ok) return json({ error: "Webhook could not be recorded." }, 503); const result = await recorded.json() as { duplicate?: boolean };
    if (!paymentId || !attemptId) return json({ received: true, duplicate: Boolean(result.duplicate), syntheticTest: true, accountMatchesBrand, paymentIdentified: false });
    try { const completion = await reconcile(brandId, attemptId, paymentId); return json({ received: true, duplicate: Boolean(result.duplicate), syntheticTest: false, accountMatchesBrand: true, paymentIdentified: true, reconciliationState: completion.state ?? "processing", orderCompleted: completion.state === "completed" }); }
    catch (error) { console.error("whop-reconciliation", error instanceof Error ? error.message : error); return json({ error: "Payment was received but order reconciliation is pending retry." }, 503); }
  } catch (error) { console.error("whop-webhook", error instanceof Error ? error.message : error); return json({ error: "Webhook signing is not configured for this brand." }, 503); }
});
