import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const encoder=new TextEncoder(),decoder=new TextDecoder();
const SHOPIFY_VERSION="2026-07";
type Obj=Record<string,unknown>;
type ShopifyCredential={domain:string;accessToken?:string;authMethod?:string;clientId?:string;clientSecret?:string};
type WhopCredential={companyId:string;apiKey:string;webhookSecret?:string};
class HttpError extends Error{constructor(public status:number,message:string){super(message);}}
function json(data:unknown,status=200){return Response.json(data,{status,headers:{"Cache-Control":"no-store","X-Content-Type-Options":"nosniff"}});}
function obj(v:unknown):Obj{return v&&typeof v==="object"&&!Array.isArray(v)?v as Obj:{};}
function fromB64url(v:string){const n=v.replace(/-/g,"+").replace(/_/g,"/"),p=n+"=".repeat((4-n.length%4)%4),b=atob(p);return Uint8Array.from(b,c=>c.charCodeAt(0));}
function internalRole(req:Request){const raw=req.headers.get("authorization")||"",token=raw.startsWith("Bearer ")?raw.slice(7):"",parts=token.split(".");if(parts.length!==3)return false;try{const payload=JSON.parse(decoder.decode(fromB64url(parts[1]))) as Obj;return payload.role==="service_role";}catch{return false;}}
async function rest(path:string,init:RequestInit={}){const base=Deno.env.get("SUPABASE_URL")!,service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;return fetch(`${base}/rest/v1/${path}`,{...init,headers:{apikey:service,Authorization:`Bearer ${service}`,"Content-Type":"application/json",...(init.headers||{})}});}
async function rpc<T=unknown>(name:string,body:Obj):Promise<T>{const r=await rest(`rpc/${name}`,{method:"POST",body:JSON.stringify(body)});if(!r.ok){let m="reconciliation_state_error";try{const p=await r.json() as Obj;if(typeof p.message==="string")m=p.message;}catch{}throw new HttpError(/busy|conflict|claimed|mismatch|expired/.test(m)?409:503,m);}if(r.status===204)return undefined as T;return await r.json() as T;}
let keyPromise:Promise<CryptoKey>|null=null;
async function cryptoKey(){if(keyPromise)return keyPromise;keyPromise=(async()=>{const r=await rest("limitless_provider_crypto_material?id=eq.production&select=key_jwk");if(!r.ok)throw new HttpError(503,"credential key unavailable");const rows=await r.json() as Array<{key_jwk?:JsonWebKey}>,k=typeof rows[0]?.key_jwk?.k==="string"?rows[0]!.key_jwk!.k!:"",raw=fromB64url(k);if(raw.byteLength!==32)throw new HttpError(503,"credential key unavailable");return crypto.subtle.importKey("raw",raw,{name:"AES-GCM"},false,["decrypt"]);})();try{return await keyPromise;}catch(e){keyPromise=null;throw e;}}
async function credential<T>(brandId:string,provider:"shopify"|"whop"):Promise<T>{const r=await rest(`limitless_provider_credentials_v2?brand_id=eq.${encodeURIComponent(brandId)}&provider=eq.${provider}&select=iv,ciphertext`);if(!r.ok)throw new HttpError(503,`${provider} credential unavailable`);const rows=await r.json() as Array<{iv?:string;ciphertext?:string}>,row=rows[0];if(!row?.iv||!row?.ciphertext)throw new HttpError(409,`${provider} credential missing`);try{const d=await crypto.subtle.decrypt({name:"AES-GCM",iv:fromB64url(row.iv),additionalData:encoder.encode(`limitless:${brandId}:${provider}:v2`)},await cryptoKey(),fromB64url(row.ciphertext));return JSON.parse(decoder.decode(d)) as T;}catch{throw new HttpError(503,`${provider} credential decrypt failed`);}}
async function context(brandId:string,attempt:Obj){if(attempt.runtimeVersion!==3||typeof attempt.contextIv!=="string"||typeof attempt.contextCiphertext!=="string")throw new HttpError(409,"unsupported payment runtime");try{const d=await crypto.subtle.decrypt({name:"AES-GCM",iv:fromB64url(attempt.contextIv),additionalData:encoder.encode(`limitless:${brandId}:payment-context:v3`)},await cryptoKey(),fromB64url(attempt.contextCiphertext));return JSON.parse(decoder.decode(d)) as {email:string;quote:{draftInput:Obj;totals:Obj};personalizationRefs:string[]};}catch{throw new HttpError(409,"payment context could not be verified");}}
async function providerFetch(url:string,init:RequestInit){let r:Response;try{r=await fetch(url,{...init,redirect:"error",cache:"no-store",signal:AbortSignal.timeout(15000)});}catch{throw new HttpError(502,"provider unavailable");}if(r.status===401||r.status===403)throw new HttpError(422,"provider rejected credentials");if(r.status===429)throw new HttpError(429,"provider rate limit");if(!r.ok)throw new HttpError(502,`provider HTTP ${r.status}`);try{return await r.json() as Obj;}catch{throw new HttpError(502,"provider invalid response");}}
function whopCents(v:unknown){if(typeof v!=="number"||!Number.isFinite(v))throw new HttpError(502,"Whop amount invalid");const scaled=v*100,c=Math.round(scaled);if(!Number.isSafeInteger(c)||Math.abs(scaled-c)>0.000001)throw new HttpError(502,"Whop amount invalid");return c;}
async function verifyWhop(c:WhopCredential,attempt:Obj,paymentId:string){const p=await providerFetch(`https://api.whop.com/api/v1/payments/${encodeURIComponent(paymentId)}`,{headers:{Authorization:`Bearer ${c.apiKey}`,Accept:"application/json","Api-Version-Date":"2026-08-21-1"}}),company=obj(p.company),metadata=obj(p.metadata);if(p.id!==paymentId||company.id!==c.companyId||p.currency!=="usd"||p.total===null||whopCents(p.total)!==Number(attempt.totalCents)||metadata.limitless_attempt_id!==attempt.id||p.checkout_configuration_id!==attempt.checkoutId)throw new HttpError(409,"Whop payment does not match this checkout attempt");if(p.status!=="paid"||p.substatus!=="succeeded")throw new HttpError(409,"Whop payment is not successfully paid");}
const tokenCache=new Map<string,{token:string;expiresAt:number}>();
async function shopifyToken(c:ShopifyCredential,refresh=false){if(c.authMethod!=="client_credentials"){if(!c.accessToken)throw new HttpError(503,"Shopify token missing");return c.accessToken;}if(!c.clientId||!c.clientSecret)throw new HttpError(503,"Shopify app credentials missing");const k=`${c.domain}|${c.clientId}`,cached=tokenCache.get(k);if(!refresh&&cached&&cached.expiresAt>Date.now()+60000)return cached.token;const p=await providerFetch(`https://${c.domain}/admin/oauth/access_token`,{method:"POST",headers:{Accept:"application/json","Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"client_credentials",client_id:c.clientId,client_secret:c.clientSecret}).toString()}),token=typeof p.access_token==="string"?p.access_token:"",seconds=Number(p.expires_in);if(!token||!Number.isInteger(seconds)||seconds<61)throw new HttpError(502,"Shopify token invalid");tokenCache.set(k,{token,expiresAt:Date.now()+seconds*1000});return token;}
async function shopifyGraphql(c:ShopifyCredential,query:string,variables:Obj={}){const call=async(refresh=false):Promise<Obj>=>{let r:Response;try{r=await fetch(`https://${c.domain}/admin/api/${SHOPIFY_VERSION}/graphql.json`,{method:"POST",headers:{"Content-Type":"application/json","X-Shopify-Access-Token":await shopifyToken(c,refresh)},body:JSON.stringify({query,variables}),redirect:"error",cache:"no-store",signal:AbortSignal.timeout(15000)});}catch{throw new HttpError(502,"Shopify unavailable");}if((r.status===401||r.status===403)&&!refresh&&c.authMethod==="client_credentials")return call(true);if(r.status===429)throw new HttpError(429,"Shopify rate limit");if(!r.ok)throw new HttpError(502,`Shopify HTTP ${r.status}`);const p=await r.json() as Obj;if(!p.data||(Array.isArray(p.errors)&&p.errors.length))throw new HttpError(422,"Shopify rejected reconciliation");return p.data as Obj;};return call();}
function usdCents(v:unknown){if(typeof v!=="string"||!/^(0|[1-9]\d*)(?:\.\d{1,2})?$/.test(v))throw new HttpError(502,"Shopify amount invalid");const[w,f=""]=v.split("."),c=Number(w)*100+Number(f.padEnd(2,"0"));if(!Number.isSafeInteger(c))throw new HttpError(502,"Shopify amount invalid");return c;}
function bagCents(raw:unknown){const b=obj(raw),s=obj(b.shopMoney),p=obj(b.presentmentMoney);if(s.currencyCode!=="USD"||p.currencyCode!=="USD")throw new HttpError(409,"Shopify currency changed");const a=usdCents(s.amount),c=usdCents(p.amount);if(a!==c)throw new HttpError(409,"Shopify price currencies diverged");return c;}
function attrs(raw:unknown){return Array.isArray(raw)?raw.flatMap(v=>{const o=obj(v);return typeof o.key==="string"&&typeof o.value==="string"?[{key:o.key,value:o.value}]:[];}).sort((a,b)=>`${a.key}\0${a.value}`.localeCompare(`${b.key}\0${b.value}`)):[];}
function lineKey(variantId:string,quantity:number,attributes:unknown){return JSON.stringify({variantId,quantity,customAttributes:attrs(attributes)});}
const moneyFields=`shopMoney{amount currencyCode} presentmentMoney{amount currencyCode}`;
const draftFields=`id status email reserveInventoryUntil customAttributes{key value} totalPriceSet{${moneyFields}} totalTaxSet{${moneyFields}} totalShippingPriceSet{${moneyFields}} shippingAddress{firstName lastName address1 address2 city zip provinceCode countryCodeV2} lineItems(first:100){nodes{variant{id} quantity title customAttributes{key value}} pageInfo{hasNextPage}} order{id displayFinancialStatus}`;
function expectedLines(input:Obj){const lines=Array.isArray(input.lineItems)?input.lineItems.map(obj):[];return lines.map(l=>l.variantId?lineKey(String(l.variantId),Number(l.quantity),l.customAttributes):JSON.stringify({priority:true,quantity:Number(l.quantity),customAttributes:[]})).sort();}
function validateDraft(raw:unknown,binding:{attemptId:string;email:string;expiresAt:number;quote:{draftInput:Obj;totals:Obj}},requireReservation=true){const d=obj(raw);if(!/^gid:\/\/shopify\/DraftOrder\/[1-9]\d*$/.test(String(d.id||"")))throw new HttpError(502,"Shopify draft incomplete");if(String(d.email||"").toLowerCase()!==binding.email.toLowerCase()||!attrs(d.customAttributes).some(a=>a.key==="limitless_attempt_id"&&a.value===binding.attemptId))throw new HttpError(409,"Shopify draft identity mismatch");if(bagCents(d.totalPriceSet)!==Number(binding.quote.totals.totalCents)||bagCents(d.totalTaxSet)!==Number(binding.quote.totals.taxCents)||bagCents(d.totalShippingPriceSet)!==0)throw new HttpError(409,"Shopify draft totals changed");const e=obj(binding.quote.draftInput.shippingAddress),a=obj(d.shippingAddress);for(const k of["firstName","lastName","address1","address2","city","zip","provinceCode"]){if(String(a[k]??"")!==String(e[k]??""))throw new HttpError(409,"Shopify draft address changed");}if(a.countryCodeV2!==e.countryCode)throw new HttpError(409,"Shopify draft country changed");const lo=obj(d.lineItems),nodes=Array.isArray(lo.nodes)?lo.nodes.map(obj):[],actual=nodes.map(l=>{const v=obj(l.variant);return v.id?lineKey(String(v.id),Number(l.quantity),l.customAttributes):l.title==="Priority processing"?JSON.stringify({priority:true,quantity:Number(l.quantity),customAttributes:attrs(l.customAttributes)}):"unsupported";}).sort();if(obj(lo.pageInfo).hasNextPage===true||JSON.stringify(expectedLines(binding.quote.draftInput))!==JSON.stringify(actual))throw new HttpError(409,"Shopify draft items changed");const order=obj(d.order);if(d.status==="COMPLETED"){if(!order.id||order.displayFinancialStatus!=="PAID")throw new HttpError(409,"Shopify order is not marked paid");}else{const reserve=typeof d.reserveInventoryUntil==="string"?Date.parse(d.reserveInventoryUntil):NaN;if(order.id||(requireReservation&&(!Number.isFinite(reserve)||reserve<binding.expiresAt)))throw new HttpError(409,"Shopify reservation expired");}return d;}
async function completeDraft(c:ShopifyCredential,binding:{attemptId:string;email:string;expiresAt:number;quote:{draftInput:Obj;totals:Obj}},draftId:string){const data=await shopifyGraphql(c,`query ReconcileDraft($id:ID!){draftOrder(id:$id){${draftFields}}}`,{id:draftId}),draft=validateDraft(data.draftOrder,binding),existing=obj(draft.order);if(existing.id)return existing;if(Date.now()>=binding.expiresAt)throw new HttpError(409,"Inventory reservation expired; paid order requires review");const completed=await shopifyGraphql(c,`mutation ReconcileComplete($id:ID!){draftOrderComplete(id:$id){draftOrder{${draftFields}} userErrors{message}}}`,{id:draftId}),root=obj(completed.draftOrderComplete);if(Array.isArray(root.userErrors)&&root.userErrors.length)throw new HttpError(409,"Shopify completion needs reconciliation");const verified=validateDraft(root.draftOrder,binding,false),order=obj(verified.order);if(!order.id)throw new HttpError(409,"Shopify completion not confirmed");return order;}
async function reconcile(brandId:string,attemptId:string,paymentId:string){if(!/^brand_[A-Za-z0-9-]+$/.test(brandId)||!/^attempt_[0-9a-f-]{36}$/.test(attemptId)||!/^pay_[A-Za-z0-9]+$/.test(paymentId))throw new HttpError(422,"invalid reconciliation reference");let attempt=await rpc<Obj|null>("limitless_checkout_payment_get",{p_brand_id:brandId,p_attempt_id:attemptId});if(!attempt)throw new HttpError(404,"payment attempt not found");const brand=await rpc<Obj|null>("limitless_checkout_brand_by_id",{p_brand_id:brandId});if(!brand)throw new HttpError(404,"brand not found");const shopify=await credential<ShopifyCredential>(brandId,"shopify"),whop=await credential<WhopCredential>(brandId,"whop"),shopifyState=obj(brand.shopify),whopState=obj(brand.whop);if(shopifyState.status!=="verified"||shopifyState.account!==shopify.domain||whopState.status!=="verified"||whopState.account!==whop.companyId||attempt.shopifyDomain!==shopify.domain||attempt.whopCompanyId!==whop.companyId)throw new HttpError(409,"payment provider account mismatch");if(!attempt.checkoutId||!attempt.draftId)throw new HttpError(409,"payment attempt is not fully bound");await verifyWhop(whop,attempt,paymentId);attempt=await rpc<Obj>("limitless_checkout_payment_accept",{p_brand_id:brandId,p_attempt_id:attemptId,p_payment_id:paymentId,p_now_ms:Date.now()});if(attempt.state==="completed"||attempt.state==="review")return{state:attempt.state,orderId:attempt.orderId||null};if(attempt.state!=="paid")throw new HttpError(409,"verified payment did not enter paid state");const lease=crypto.randomUUID();try{attempt=await rpc<Obj>("limitless_checkout_payment_claim_completion",{p_brand_id:brandId,p_attempt_id:attemptId,p_lease_token:lease,p_now_ms:Date.now()});}catch(e){if(e instanceof HttpError&&e.message.includes("completion_busy"))return{state:"processing",orderId:null};throw e;}const saved=await context(brandId,attempt),binding={attemptId,email:saved.email,expiresAt:Number(attempt.expiresAt),quote:saved.quote};const order=await completeDraft(shopify,binding,String(attempt.draftId)),orderId=String(order.id||"");if(saved.personalizationRefs?.length)await rpc("limitless_checkout_finalize_personalizations",{p_brand_id:brandId,p_refs:saved.personalizationRefs,p_attempt_id:attemptId,p_order_id:orderId});attempt=await rpc<Obj>("limitless_checkout_payment_complete",{p_brand_id:brandId,p_attempt_id:attemptId,p_order_id:orderId,p_lease_token:lease});const lines=Array.isArray(saved.quote.draftInput.lineItems)?saved.quote.draftInput.lineItems.map(obj):[];await rpc("limitless_checkout_record_order",{p_brand_id:brandId,p_order_id:orderId,p_order:{id:orderId,brandId,customer:saved.email,email:saved.email,total:Number(attempt.totalCents)/100,currency:"USD",status:"paid",syncStatus:"synced",mode:"live",items:lines.map(l=>({variantId:l.variantId||null,title:l.title||null,quantity:Number(l.quantity||0)})),whopPaymentId:paymentId,createdAt:new Date().toISOString()}});return{state:"completed",orderId};}
Deno.serve(async(req:Request)=>{if(req.method!=="POST")return json({error:"Method not allowed."},405);if(!internalRole(req))return json({error:"Unauthorized."},401);let p:Obj;try{p=await req.json() as Obj;}catch{return json({error:"Invalid request."},400);}try{return json(await reconcile(String(p.brandId||""),String(p.attemptId||""),String(p.paymentId||"")));}catch(e){if(e instanceof HttpError)return json({error:e.message},e.status);console.error("payment-reconciler",e);return json({error:"Payment reconciliation is temporarily unavailable."},503);}});
